global:
  scrape_interval: 5s
  evaluation_interval: 5s
rule_files:
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ '127.0.0.1:9090']
  - job_name: 'prompring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['prompring:9000']
  - job_name: 'docker'
    static_configs:
      - targets: ['docker.for.mac.host.internal:9323']